---
- name: Retrieve data from csv file
  set_fact:
    raw_path_data: "{{ lookup('file', 'link_data_file').split('\n') }}"
    path_data: []

- debug: var=raw_path_data

- name: Convert raw data to j2 input data - list of list
  set_fact:
    path_data: "{{ path_data + [ line.split(',') ] }}"
  loop: "{{ raw_path_data }}"
  loop_control:
    loop_var: line

- debug: var=path_data

- name: Generate body data for KIE call
  ansible.builtin.template:
    src: input.j2
    dest: roles/troubleshoot/files/input.json
    #dest: input.json

- name: Call KIE
  ansible.builtin.uri:
    url: "{{ rule_base_url }}"
    method: POST
    status_code: [201, 200]
    return_content: true
    validate_certs: no
    headers:
      accept: application/json
      Content-Type: application/json
    body_format: json
    body: "{{ lookup('ansible.builtin.file','input.json') }}"
  register: result


- debug: var=result

- name: Set next task
  set_fact:
    next_task: "{{ result['json'] }}"

