---
- name: Apply the recommendataion
  hosts: all
  gather_facts: false
  vars:
    tasks_results:
#      'Memory_Issue': 1
      'Antivirus_Scan_Issue': 1
      'SQL_Memory_Issue': 1
      'OS_Memory_Issue': 1
      'Network_GateWay_Issue': 0
      'Web_Pool_Issue': 0
      'Log_Ticket': 0
      'Stop_Delay_Scan': 0
      'Clean_DB_Memory_Heap': 0
      'Flush_OS_Cache_Memory': 0
      'Fix_Default_Gateway': 0
      'Fix_WebApp_connection_Pools': 0


    source_files: 
      - '/root/ansi/files/App_Slow_Knowledge_Map'
      - '/root/ansi/files/link_data_file'

    init_knowledge_map_dir: '/tmp/192.168.122.51/root/ansi/files'

    sub_workflow_with_rule_base: 
    - Memory_Issue

  tasks:

  - set_fact:
      excuted_tasks: []

  - include_tasks: 02-01-execute-recommendation.yaml
