---
- name: Store file into /tmp/192.168.122.51/{{ home_dir }}
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: /tmp
  loop: "{{ source_files }}"
  when: "inventory_hostname == '192.168.122.51'"
  register: result

- debug: var=result

- name: tasks on localhost
  block:
     - name: use the initial knowledge map on local host
       shell: |
         grep "^[A-Z,a-z]" {{ init_knowledge_map_dir }}/App_Slow_Knowledge_Map > {{ init_knowledge_map_dir }}/link_data_file
       when: "inventory_hostname == 'localhost'"
     
     - name: use the initial knowledge map on local host
       shell: |
         grep "^[A-Z,a-z]" {{ source_files[0] }} > {{ source_files[1] }}
       when: "inventory_hostname == '192.168.122.51'"
  when:  
    - map_init is defined
    - map_init | bool
