---
- name: Store file into /tmp/192.168.122.51/{{ home_dir }}
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: /tmp
  loop: "{{ source_files }}"
  when: "inventory_hostname == '192.168.122.51'"
  register: result

- debug: var=result

- name: tasks on localhost
  block:
     - name: use the initial knowledge map
       shell: |
         cp {{ init_knowledge_map_dir }}/App_Slow_Knowledge_Map  {{ init_knowledge_map_dir }}/link_data_file
       when:  
         - map_init is defined
         - map_init | bool
       register: result
     
     - debug: var=result
     
     - debug:
         msg: "{{ map_init }}"
     
  when: "inventory_hostname == 'localhost'"
